#!/bin/bash


# Copyright (c) 2021 by Philip Collier, github.com/AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# Run this script as a regular user

main(){
IPTABLES_BACKUP="/tmp/iptables.backup"
OPTION1="Connect"
OPTION2="Disconnect"
OPTION3="Switch Server"
OPTION4="Import configs"
OPTION5="Quit"

OPTIONS="$OPTION1\n$OPTION2\n$OPTION3\n$OPTION4\n$OPTION5"

SELECTED="$(echo -e "$OPTIONS" | rofi -lines 5 -dmenu -p "Wireguard VPN")"

connect(){
    [[ -f "$IPTABLES_BACKUP" ]] || sudo iptables-save | sudo tee $IPTABLES_BACKUP
    basename -s .conf $(ls /etc/wireguard) | rofi -dmenu -p "Select to connect" | \
    xargs -I {} wg-quick up "{}"
}

disconnect(){ 
    wg 2>&1 | grep interface | awk '{print $5}' | sed 's/://g' | \
        rofi -dmenu -p "Select to disconnect"| xargs -I {} wg-quick down "{}"
    [[ -f "$IPTABLES_BACKUP" ]] && sudo iptables-save | sudo tee $IPTABLES_BACKUP
}

switch(){
    # make selections
    out_server="$(wg 2>&1 | grep interface | awk '{print $5}' | sed 's/://g' | \
        rofi -dmenu -p "Select to disconnect")"
    in_server="$(basename -s .conf $(ls /etc/wireguard) | rofi -dmenu -p "Select to connect")"
    # break then make connection
    wg-quick down "${out_server}"; wg-quick up "${in_server}"
    [[ -f "$IPTABLES_BACKUP" ]] || sudo iptables-save | sudo tee $IPTABLES_BACKUP
}

import(){
    fd -d 2 -t file -e conf . | \
    rofi -dmenu -p "Select to copy" -multi-select -mesg "Shift + Enter to multi select" | \
    xargs -I{} sudo cp -f "{}" /etc/wireguard/; sudo chmod 640 /etc/wireguard/*.conf
    main
}

case $SELECTED in
  $OPTION1)
    # connect
    connect
    exit 0
	;;
  $OPTION2)
    # disconnect
    disconnect
    main
    ;;
  $OPTION3)
    # switch
    switch 
    exit 0
    ;;
  $OPTION4)
    # copy conf files
    import
    ;;
  $OPTION5)
    # exit the script
    exit 0
    ;;
esac
}

main
